### ISSUE TITLE
[DHF-01C] Inefficient Application of Region Pause Status Enforcement

### ISSUE THREAD

**Issue by zajck** [bosonprotocol/boson-protocol-contracts#511]
## DHF-01C: Inefficient Application of Region Pause Status Enforcement

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Gas Optimization](/appendix/finding-types#gas-optimization) | <img class="o-severity o-informational" src="https://omniscia.io/report-assets/informational.png" /> | DisputeHandlerFacet.sol:L67, [L166](https://github.com/bosonprotocol/boson-protocol-contracts/blob/38c7ba384e55486aee4ea76bb80b4f29d1a86175/contracts/protocol/facets/DisputeHandlerFacet.sol#L166), [L202](https://github.com/bosonprotocol/boson-protocol-contracts/blob/38c7ba384e55486aee4ea76bb80b4f29d1a86175/contracts/protocol/facets/DisputeHandlerFacet.sol#L202), [L235](https://github.com/bosonprotocol/boson-protocol-contracts/blob/38c7ba384e55486aee4ea76bb80b4f29d1a86175/contracts/protocol/facets/DisputeHandlerFacet.sol#L235), [L345](https://github.com/bosonprotocol/boson-protocol-contracts/blob/38c7ba384e55486aee4ea76bb80b4f29d1a86175/contracts/protocol/facets/DisputeHandlerFacet.sol#L345), [L381](https://github.com/bosonprotocol/boson-protocol-contracts/blob/38c7ba384e55486aee4ea76bb80b4f29d1a86175/contracts/protocol/facets/DisputeHandlerFacet.sol#L381), [L441](https://github.com/bosonprotocol/boson-protocol-contracts/blob/38c7ba384e55486aee4ea76bb80b4f29d1a86175/contracts/protocol/facets/DisputeHandlerFacet.sol#L441), [L443](https://github.com/bosonprotocol/boson-protocol-contracts/blob/38c7ba384e55486aee4ea76bb80b4f29d1a86175/contracts/protocol/facets/DisputeHandlerFacet.sol#L443) |

### Description:

The `disputesNotPaused` modifier is introduced throughout the functions of the `DisputeHandlerFacet`, however, this replication is unnecessary as it can be made optimal as well as more efficient.

### Example:

```solidity
/**
 * @notice Expires the dispute and releases the funds.
 *
 * Emits a DisputeExpired event if successful.
 *
 * Reverts if:
 * - The disputes region of protocol is paused
 * - Exchange does not exist
 * - Exchange is not in a Disputed state
 * - Dispute is still valid
 * - Dispute is in some state other than Resolving
 *
 * @param _exchangeId - the id of the associated exchange
 */
function expireDispute(uint256 _exchangeId) public override disputesNotPaused nonReentrant {
    // Get the exchange, should be in disputed state
    (Exchange storage exchange, ) = getValidExchange(_exchangeId, ExchangeState.Disputed);

    // Fetch the dispute and dispute dates
    (, Dispute storage dispute, DisputeDates storage disputeDates) = fetchDispute(_exchangeId);

    // Make sure the dispute is in the resolving state
    require(dispute.state == DisputeState.Resolving, INVALID_STATE);

    // make sure the dispute not expired already
    require(block.timestamp > disputeDates.timeout, DISPUTE_STILL_VALID);

    // Finalize the dispute
    finalizeDispute(_exchangeId, exchange, dispute, disputeDates, DisputeState.Retracted, 0);

    // Notify watchers of state change
    emit DisputeExpired(_exchangeId, msgSender());
}

/**
 * @notice Expires a batch of disputes and releases the funds.
 *
 * Emits a DisputeExpired event for every dispute if successful.
 *
 * Reverts if:
 * - The disputes region of protocol is paused
 * - Number of disputes exceeds maximum allowed number per batch
 * - For any dispute:
 *   - Exchange does not exist
 *   - Exchange is not in a Disputed state
 *   - Dispute is still valid
 *   - Dispute is in some state other than Resolving
 *
 * @param _exchangeIds - the array of ids of the associated exchanges
 */
function expireDisputeBatch(uint256[] calldata _exchangeIds) external override disputesNotPaused {
    // limit maximum number of disputes to avoid running into block gas limit in a loop
    require(_exchangeIds.length <= protocolLimits().maxDisputesPerBatch, TOO_MANY_DISPUTES);

    for (uint256 i = 0; i < _exchangeIds.length; i++) {
        // create offer and update structs values to represent true state
        expireDispute(_exchangeIds[i]);
    }
}
```

### Recommendation:

The `disputesNotPaused` modifier can be relocated to the `finalizeDispute` function that is invoked by all current functions of the contract that apply the modifier (sans `extendDisputeTimeout` where it should remain). Additionally, in the current iteration the `disputesNotPaused` modifier is applied multiple times redundantly by the `expireDisputeBatch` function as it is validated once at the top level and consequently at each `expireDispute` invocation. This would require a revamp of how the internal functions of the contract work to properly optimize.

**Comment by mischat** [comment]
OK, this looks OK to me, this doesn't do the revamp of the code, to optimise the `expireDisputeBatch`, but that is fine for now. Perhaps we could log this as an enhance in the issues sections, so we don't forget about it in the future?
