### ISSUE TITLE
Commit to offer doesn't check for voided

### ISSUE THREAD

**Issue by davebryson** [bosonprotocol/boson-protocol-contracts#565]
Commit to offer doesn't appear to check if the offer has been voided: [ExchangeHandlerFacet](https://github.com/bosonprotocol/boson-protocol-contracts/blob/main/contracts/protocol/facets/ExchangeHandlerFacet.sol#L76) 

This is because [ProtocalBase.fetchOffer](https://github.com/bosonprotocol/boson-protocol-contracts/blob/main/contracts/protocol/bases/ProtocolBase.sol#L378) does not check for `voided`

Is this the intended behavior?

**Comment by anajuliabit** [comment]
Hello @davebryson!

We don't check within the `fetchOffer` method, but we do check in the `commitToOfferInternal` method. Additionally, we have another method, `getValidOffer`, which we use when we need this kind of check.

Thanks for bringing this up!

**Comment by anajuliabit** [comment]
I would appreciate it if you could close this issue, as it doesn't seem to be valid. If you have any additional questions, please don't hesitate to reach out to us. We're always available to help and are more than happy to provide further assistance.
