### ISSUE TITLE
Boson voucher owner should not be able to renounceOwnership

### ISSUE THREAD

**Issue by zajck** [bosonprotocol/boson-protocol-contracts#588]
### Description:

`BosonVoucher` inherits `OwnableUpgradeable` which implements method `renounceOwnership()`. If owner calls it, it loses its owner privileges, therefore it can no longer call methods with `onlyOwner` modifier. Affected functions are `preMint`, `burnPremintedVouchers`, `setContractURI`, `callExternalContract` and `setApprovalForAllToContract`.

If that happens, seller is not totally broken, since updating assistant address in the protocol also sets it as a new contract owner. Therefore this is then merely an inconvenience that can happen. It is still better to prevent it. 

Also, since `transferOwnership` is restricted (owner cannot call it directly) it does not make sense to leave a similar function unrestricted. Most likely renouncing ownership should be part of acount deactivation inside the protocol.

### Recommendation:
Override `renounceOwnership()` in `BosonVoucher` and revert if it is called.

**Comment by mischat** [comment]
I agree with this, especially given that updating the assistant will always impact the ownership of the vouchers, probably worth just making this action do nothing for now.

**Comment by mischat** [comment]
Good find
