### ISSUE TITLE
RoyaltyPecentage typo

### ISSUE THREAD

**Issue by zajck** [bosonprotocol/boson-protocol-contracts#594]
The code contains the same typo `RoyaltyPecentage` in multiple places.

In most cases it's just a variable name, so changing it won't affect the bytecode.

There are two methods in Config Handler that will be affected `setMaxRoyaltyPecentage`, `getMaxRoyaltyPecentage`, but since they are not actively used, this should also present no problem if they are changed.

**Comment by mischat** [comment]
This doesn't need to get into v2.2 does it ?

**Comment by zajck** [comment]
No. Probably it could be resolved in #579 which already deals with royalties.
