### ISSUE TITLE
Remove redundant check on createTwinInternal

### ISSUE THREAD

**Issue by anajuliabit** [bosonprotocol/boson-protocol-contracts#596]
The code block at [https://github.com/bosonprotocol/boson-protocol-contracts/blob/100b9b05599f12a77b93f9e7986c207df93e4ab9/contracts/protocol/bases/TwinBase.sol#L79-L93](https://github.com/bosonprotocol/boson-protocol-contracts/blob/100b9b05599f12a77b93f9e7986c207df93e4ab9/contracts/protocol/bases/TwinBase.sol#L79-L93) is redundant and should be removed. 

The check for overlapping twins is already performed on lines [https://github.com/bosonprotocol/boson-protocol-contracts/blob/100b9b05599f12a77b93f9e7986c207df93e4ab9/contracts/protocol/bases/TwinBase.sol#L100-L106](https://github.com/bosonprotocol/boson-protocol-contracts/blob/100b9b05599f12a77b93f9e7986c207df93e4ab9/contracts/protocol/bases/TwinBase.sol#L100-L106), so it is not necessary to perform it on lines 79-93.

The lookup `twinIdsByTokenAddressAndBySeller` should be deprecated, as it is only used for this code block.

**Comment by mischat** [comment]
@anajuliabit, in your description above, you say that the lines 

Lines 79 to 93 in [100b9b0](https://github.com/bosonprotocol/boson-protocol-contracts/commit/100b9b05599f12a77b93f9e7986c207df93e4ab9)

could be removed, as the check happens on (the same) lines : 

Lines 79 to 93 in [100b9b0](https://github.com/bosonprotocol/boson-protocol-contracts/commit/100b9b05599f12a77b93f9e7986c207df93e4ab9). 

Could you please link to where the check is already happenings for me, as it will make it easier for me to review the resultant PR, thanks?

**Comment by anajuliabit** [comment]
@mischat sorry, description updated

**Comment by mischat** [comment]
thanks, this will make it easier for me to review! 👍
