### ISSUE TITLE
Why do we have a truffle.js file in the repo ?

### ISSUE THREAD

**Issue by mischat** [bosonprotocol/boson-protocol-contracts#618]
Why do we have ```truffle-config.js``` in the repo ?

**Comment by zajck** [comment]
`docgen` is using truffle's artifacts to create documentation. Whenever it's run, contracts are compiled with truffle and removed automatically after the doc is generated.

https://github.com/bosonprotocol/boson-protocol-contracts/blob/59d6c6a05c2d3c30f5e3b6bea03bd6765843fb86/package.json#L30

**Comment by mischat** [comment]
thanks
