### ISSUE TITLE
Resolution Period

### ISSUE THREAD

**Issue by mischat** [bosonprotocol/boson-protocol-contracts#671]
We should be setting a global minimum for the Resolution Period, so that Seller can't create an offer that automatically defaults/timesout the buyer, and sends all of the monies to the Seller.

**Comment by mischat** [comment]
@zajck would be good to get a feel for how much work this would be and whether or not it would be feasible to squeeze this into v2.3.0 ?

**Comment by zajck** [comment]
> @zajck would be good to get a feel for how much work this would be and whether or not it would be feasible to squeeze this into v2.3.0 ?

@mischat Since it's everything just more or less the copy of the pattern we have for the minimal Dispute Period this is less than a day of coding. Totally feasible for v2.3.0

**Comment by mischat** [comment]
Then i think we should do it. @zajck, is that something you can pick up ?

**Comment by zajck** [comment]
^^ linked PR #673 already fixes it.
