### ISSUE TITLE
Unpredictable fees in createOffer

### ISSUE THREAD

**Issue by zajck** [bosonprotocol/boson-protocol-contracts#683]
It’s possible that when the seller creates an offer, they get charged different fees than expected when they submit the `createOffer` transaction.

This can happen if they submit createOffer at approximately the same time as one of the methods that affect fees (`setProtocolFeePercentage`, `setProtocolFeeFlatBoson` or `updateAgent`) is submitted and `createOffer` is included in a block after the other call.
The fee change happens immediately and when the offer is created fees are retrieved from the storage (the seller does not explicitly put them as input).

So it could be simply a racing condition or even a front-running (if the protocol/agent is malicious) that results in a different offer than expected.

The severity is low since the seller can always void the offer if it’s not as expected, but it would be nice to prevent it if possible, especially since the seller might not even notice the fee changed.

#### Opt1: The seller submits the maximum fee they are willing to pay
An additional argument is added to all `createOffer` methods, where the seller provides max fee they accept. If one of the fees changes before `createOffer` is mined, two outcomes are possible:
- The new fee is higher than the maximum fee. In this case, the transaction is reverted
- The new fee is lower or equal to the maximum fee. The new fee is applied.

#### Opt2: Fee change delay
When a fee change is submitted to the protocol, it’s not applied immediately, but after some time period. During that period, old fees are used in the same way as they are now.  
It requires coming up with some sensible delay period.

**Comment by zajck** [comment]
The team decided to remediate it with option 1. 

Methods that create offers should accept a parameter with a maximum acceptable fee, denominated in the offer's exchange token.
If `agentFeeAmount + protocolFee` is more than it, offer creation should fail.

**Comment by mischat** [comment]
To evaluate whether or not we want to pause the agent's region until after this fix ...
