### ISSUE TITLE
Missing reentrancy guard

### ISSUE THREAD

**Issue by zajck** [bosonprotocol/boson-protocol-contracts#762]
`setAllowlistedFunctions` is missing the reentrancy guard, which under certain circumstances allows the attacker to impersonate the admin account and modify the allow list.

https://github.com/bosonprotocol/boson-protocol-contracts/blob/9070c0484634cec7bec793808a43ca20616d889a/contracts/protocol/facets/MetaTransactionsHandlerFacet.sol#L339-L342

#### Recommendation

Add the reentrancy guard.

**Comment by mischat** [comment]
Good catch here.
