### ISSUE TITLE
Unable to Deploy Contracts to Local Hardhat Node

### ISSUE THREAD

**Issue by allen-mak** [bosonprotocol/boson-protocol-contracts#947]
Hello, I have difficulty in deploying BOSON contracts to the local Hardhat node.

I used `npx hardhat node` to start a local node instance, updated `ADMIN_ADDRESS_LOCAL` and `AUTH_TOKEN_OWNERS_LOCAL` to one of the address shown when starting the node.

I could execute `npm run deploy-mocks:local` to setup the authentication tokens.

However, when I run npm run deploy-suite:local, the deployment runs for over 2 hours but shows no progress.
And, when I check the console that is running Hardhat node, and found the logs keeps repeating:
```
eth_getTransactionReceipt
eth_blockNumber
```

Please help.

**Comment by zajck** [comment]
Hi @allen-mak 

I assume that you are using the hardhat with default mining behaviour (automine) and that you are using the default value for `CONFIRMATIONS` in `.env` file. This combination leads to the script waiting for new blocks to be produced, which never happens and therefore it gets stuck.

You have two solutions:
- Try changing `CONFIRMATIONS` in `.env` from the default 3 to 1. The deployment script will continue immediately after the submitted transaction is mined
- You can change hardhat to interval mining with a chosen period of block production ( https://hardhat.org/hardhat-network/docs/reference#mining-modes ). In this case, the deployment script will wait that `CONFIRMATIONS` blocks are produced after it submits the transaction.

Option 2 is closer to real-world behaviour, however for testing purposes I'd suggest just going with option 1.
